server:
  port: 19092
  forward-headers-strategy: native # ??? ?? ?? ?? ??

spring:
  application:
    name: order
  data:
    redis:
      host: localhost
      port: 6379
      password: systempass
  cloud:
    discovery:
      enabled: true
  zipkin:
    base-url: http://localhost:9411 # Zipkin ?? URL
  main:
    allow-bean-definition-overriding: true
  sleuth:
    sampler:
      probability: 1.0 # 모든 요청 추적 활성화
  cache:
    type: caffeine # 캐시 구현체를 Caffeine으로 설정
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/oauth2/token # 인증 서버 URL
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*" # ?? Actuator ????? ??

logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    com.sparta.msa_exam.order.client.ProductClient: DEBUG


jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==
  expiration-time: 3600000
