server:
  port: 19091

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - name: AddResponseHeader
              args:
                name: Server-Port
                value: "${server.port}" # 응답 헤더에 포트를 추가
    loadbalancer:
      weighted:
        enabled: true # Weighted Load Balancing 활성화
  discovery:
    locator:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
