server:
  port: 19095

spring:
  application:
    name: auth
  data:
    redis:
      host: localhost
      port: 6379
      password: systempass
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:19095/auth
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:19093
          predicates:
            - Path=/products/**
        - id: order-service
          uri: http://localhost:19092
          predicates:
            - Path=/orders/**
    default-filters:
      - name: JwtAuthFilter
  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
    fetch-registry: true
    register-with-eureka: true

jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==
  expiration-time: 3600000

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework: INFO
